version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: run TSLint
          command: |
            npm install
            npm run tslint
